version: "3.8"

services:
  authservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authservice
    restart: unless-stopped
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=socialmedia
    networks:
      - app-network

networks:
  app-network:
    external: true
