version: "3.8"

services:
  authservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authservice
    restart: unless-stopped
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=authuser
      - DB_PASSWORD=geheim
      - DB_NAME=authdb
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres_auth
    restart: unless-stopped
    environment:
      - POSTGRES_USER=authuser
      - POSTGRES_PASSWORD=geheim
      - POSTGRES_DB=authdb
    volumes:
      - authservice_db_data:/var/lib/postgresql/data
      - ../../databases/postgresql/auth-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    ports:
      - "5433:5432"

volumes:
  authservice_db_data:

networks:
  app-network:
    external: true
