services:
  frontend:
    image: myproject/frontend:latest
    build:
      context: ./frontend      # Der Build-Kontext ist das Verzeichnis, in dem sich das Dockerfile befindet
      dockerfile: Dockerfile   # Das Dockerfile wird aus dem Kontext (./frontend) genommen

    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json

    ports:
      - "3000:80"              # Port-Mapping: Host-Port 3000 -> Container-Port 80

    environment:
      - CHOKIDAR_USEPOLLING=true