version: "3.8"

services:
  authservice:
    build:
      context: ./backend/authservice
    container_name: authservice
    restart: unless-stopped
    ports:
      - "4000:3000"    # Host-Port 4000 → Container-Port 3000
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=authuser
      - DB_PASSWORD=geheim
      - DB_NAME=authdb
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres_auth
    restart: unless-stopped
    environment:
      - POSTGRES_USER=authuser
      - POSTGRES_PASSWORD=geheim
      - POSTGRES_DB=authdb
    volumes:
      - authservice_postgres_data:/var/lib/postgresql/data
      - ./databases/postgresql/auth-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"    # Host-Port 5433 → Container-Port 5432

volumes:
  authservice_postgres_data: