# File: docker-compose.yml
version: "3.8"

services:
  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    container_name: socialmedia-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: socialmedia
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: mediaservice123
    # Nur das Daten-Volume, keine Init-Mounts mehr
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  neo4j:
    build:
      context: ./neo4j
      dockerfile: Dockerfile
    container_name: socialmedia-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/socialmedia123
      NEO4J_dbms_default__database: socialmedia
      NEO4J_PLUGINS: "[\"apoc\"]"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - app-network
    restart: unless-stopped

  socialmedia-minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
    container_name: socialmedia-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: socialmedia123
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network
    restart: unless-stopped

  minio-setup:
    image: minio/mc:latest
    container_name: socialmedia-minio-setup
    depends_on:
      - socialmedia-minio
    environment:
      MC_HOST_myminio: http://minioadmin:socialmedia123@socialmedia-minio:9000
    entrypoint: >
      /bin/sh -c "
      echo 'Warte auf MinIO...';
      sleep 10;
      mc alias set myminio http://socialmedia-minio:9000 minioadmin socialmedia123;
      mc mb myminio/images --ignore-existing;
      mc mb myminio/videos --ignore-existing;
      mc mb myminio/audio --ignore-existing;
      mc mb myminio/documents --ignore-existing;
      mc mb myminio/avatars --ignore-existing;
      mc mb myminio/thumbnails --ignore-existing;
      mc anonymous set download myminio/images;
      mc anonymous set download myminio/videos;
      mc anonymous set download myminio/audio;
      mc anonymous set download myminio/avatars;
      mc anonymous set download myminio/thumbnails;
      echo 'MinIO Setup abgeschlossen!';
      "
    networks:
      - app-network
    restart: "no"

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  minio_data:

networks:
  app-network:
    external: true
